export const starshipAdapter: Record<string, string> = {
    'name':                     'nombre',
    'model':                    'modelo',
    'manufacturer':             'fabricante',
    'cost_in_credits':          'costo_en_creditos',
    'length':                   'longitud',
    'max_atmosphering_speed':   'velocidad_maxima_en_atmosfera',
    'crew':                     'tripulacion',
    'passengers':               'pasajeros',
    'cargo_capacity':           'capacidad_de_carga',
    'consumables':              'consumibles',
    'hyperdrive_rating':        'calificación_del_hiperimpulsor',
    'MGLT':                     'MGLT',
    'starship_class':           'clase_de_nave',
    'pilots':                   'pilotos',
    'films':                    'peliculas',
    'created':                  'creado',
    'edited':                   'editado',
    'url':                      'url',
}