export const vehicleAdapter: Record<string, string> = {
    'name':                   'nombre',
    'model':                  'modelo',
    'manufacturer':           'fabricante',
    'cost_in_credits':        'costo_en_creditos',
    'length':                 'longitud',
    'max_atmosphering_speed': 'velocidad_maxima_en_atmosfera',
    'crew':                   'tripulacion',
    'passengers':             'pasajeros',
    'cargo_capacity':         'capacidad_de_carga',
    'consumables':            'consumibles',
    'vehicle_class':          'clase_de_vehículo',
    'pilots':                 'pilotos',
    'films':                  'films',
    'created':                'creado',
    'edited':                 'editado',
    'url':                    'url',
}